/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ApiextensionsV1beta1ServiceReference model module.
* @module client/client.models/ApiextensionsV1beta1ServiceReference
* @version 0.1
*/
export default class ApiextensionsV1beta1ServiceReference {
    /**
    * Constructs a new <code>ApiextensionsV1beta1ServiceReference</code>.
    * ServiceReference holds a reference to Service.legacy.k8s.io
    * @alias module:client/client.models/ApiextensionsV1beta1ServiceReference
    * @class
    * @param name {String} `name` is the name of the service. Required
    * @param namespace {String} `namespace` is the namespace of the service. Required
    */

    constructor(name, namespace) {
        

        
        

        this['name'] = name;this['namespace'] = namespace;

        
    }

    /**
    * Constructs a <code>ApiextensionsV1beta1ServiceReference</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/ApiextensionsV1beta1ServiceReference} obj Optional instance to populate.
    * @return {module:client/client.models/ApiextensionsV1beta1ServiceReference} The populated <code>ApiextensionsV1beta1ServiceReference</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiextensionsV1beta1ServiceReference();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('namespace')) {
                obj['namespace'] = ApiClient.convertToType(data['namespace'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }

    /**
    * `name` is the name of the service. Required
    * @member {String} name
    */
    name = undefined;
    /**
    * `namespace` is the namespace of the service. Required
    * @member {String} namespace
    */
    namespace = undefined;
    /**
    * `path` is an optional URL path which will be sent in any request to this service.
    * @member {String} path
    */
    path = undefined;








}


