/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ExtensionsV1beta1ScaleSpec model module.
* @module client/client.models/ExtensionsV1beta1ScaleSpec
* @version 0.1
*/
export default class ExtensionsV1beta1ScaleSpec {
    /**
    * Constructs a new <code>ExtensionsV1beta1ScaleSpec</code>.
    * describes the attributes of a scale subresource
    * @alias module:client/client.models/ExtensionsV1beta1ScaleSpec
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ExtensionsV1beta1ScaleSpec</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/ExtensionsV1beta1ScaleSpec} obj Optional instance to populate.
    * @return {module:client/client.models/ExtensionsV1beta1ScaleSpec} The populated <code>ExtensionsV1beta1ScaleSpec</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExtensionsV1beta1ScaleSpec();

            
            
            

            if (data.hasOwnProperty('replicas')) {
                obj['replicas'] = ApiClient.convertToType(data['replicas'], 'Number');
            }
        }
        return obj;
    }

    /**
    * desired number of instances for the scaled object.
    * @member {Number} replicas
    */
    replicas = undefined;








}


