/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import NetworkingV1beta1HTTPIngressPath from './NetworkingV1beta1HTTPIngressPath';





/**
* The NetworkingV1beta1HTTPIngressRuleValue model module.
* @module client/client.models/NetworkingV1beta1HTTPIngressRuleValue
* @version 0.1
*/
export default class NetworkingV1beta1HTTPIngressRuleValue {
    /**
    * Constructs a new <code>NetworkingV1beta1HTTPIngressRuleValue</code>.
    * HTTPIngressRuleValue is a list of http selectors pointing to backends. In the example: http://&lt;host&gt;/&lt;path&gt;?&lt;searchpart&gt; -&gt; backend where where parts of the url correspond to RFC 3986, this resource will be used to match against everything after the last &#39;/&#39; and before the first &#39;?&#39; or &#39;#&#39;.
    * @alias module:client/client.models/NetworkingV1beta1HTTPIngressRuleValue
    * @class
    * @param paths {Array.<module:client/client.models/NetworkingV1beta1HTTPIngressPath>} A collection of paths that map requests to backends.
    */

    constructor(paths) {
        

        
        

        this['paths'] = paths;

        
    }

    /**
    * Constructs a <code>NetworkingV1beta1HTTPIngressRuleValue</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/NetworkingV1beta1HTTPIngressRuleValue} obj Optional instance to populate.
    * @return {module:client/client.models/NetworkingV1beta1HTTPIngressRuleValue} The populated <code>NetworkingV1beta1HTTPIngressRuleValue</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkingV1beta1HTTPIngressRuleValue();

            
            
            

            if (data.hasOwnProperty('paths')) {
                obj['paths'] = ApiClient.convertToType(data['paths'], [NetworkingV1beta1HTTPIngressPath]);
            }
        }
        return obj;
    }

    /**
    * A collection of paths that map requests to backends.
    * @member {Array.<module:client/client.models/NetworkingV1beta1HTTPIngressPath>} paths
    */
    paths = undefined;








}


