/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import NetworkingV1beta1IngressBackend from './NetworkingV1beta1IngressBackend';





/**
* The NetworkingV1beta1HTTPIngressPath model module.
* @module client/client.models/NetworkingV1beta1HTTPIngressPath
* @version 0.1
*/
export default class NetworkingV1beta1HTTPIngressPath {
    /**
    * Constructs a new <code>NetworkingV1beta1HTTPIngressPath</code>.
    * HTTPIngressPath associates a path regex with a backend. Incoming urls matching the path are forwarded to the backend.
    * @alias module:client/client.models/NetworkingV1beta1HTTPIngressPath
    * @class
    * @param backend {module:client/client.models/NetworkingV1beta1IngressBackend} Backend defines the referenced service endpoint to which the traffic will be forwarded to.
    */

    constructor(backend) {
        

        
        

        this['backend'] = backend;

        
    }

    /**
    * Constructs a <code>NetworkingV1beta1HTTPIngressPath</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/NetworkingV1beta1HTTPIngressPath} obj Optional instance to populate.
    * @return {module:client/client.models/NetworkingV1beta1HTTPIngressPath} The populated <code>NetworkingV1beta1HTTPIngressPath</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkingV1beta1HTTPIngressPath();

            
            
            

            if (data.hasOwnProperty('backend')) {
                obj['backend'] = NetworkingV1beta1IngressBackend.constructFromObject(data['backend']);
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }

    /**
    * Backend defines the referenced service endpoint to which the traffic will be forwarded to.
    * @member {module:client/client.models/NetworkingV1beta1IngressBackend} backend
    */
    backend = undefined;
    /**
    * Path is an extended POSIX regex as defined by IEEE Std 1003.1, (i.e this follows the egrep/unix syntax, not the perl syntax) matched against the path of an incoming request. Currently it can contain characters disallowed from the conventional \"path\" part of a URL as defined by RFC 3986. Paths must begin with a '/'. If unspecified, the path defaults to a catch all sending traffic to the backend.
    * @member {String} path
    */
    path = undefined;








}


