/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import PolicyV1beta1IDRange from './PolicyV1beta1IDRange';





/**
* The PolicyV1beta1SupplementalGroupsStrategyOptions model module.
* @module client/client.models/PolicyV1beta1SupplementalGroupsStrategyOptions
* @version 0.1
*/
export default class PolicyV1beta1SupplementalGroupsStrategyOptions {
    /**
    * Constructs a new <code>PolicyV1beta1SupplementalGroupsStrategyOptions</code>.
    * SupplementalGroupsStrategyOptions defines the strategy type and options used to create the strategy.
    * @alias module:client/client.models/PolicyV1beta1SupplementalGroupsStrategyOptions
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PolicyV1beta1SupplementalGroupsStrategyOptions</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/PolicyV1beta1SupplementalGroupsStrategyOptions} obj Optional instance to populate.
    * @return {module:client/client.models/PolicyV1beta1SupplementalGroupsStrategyOptions} The populated <code>PolicyV1beta1SupplementalGroupsStrategyOptions</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PolicyV1beta1SupplementalGroupsStrategyOptions();

            
            
            

            if (data.hasOwnProperty('ranges')) {
                obj['ranges'] = ApiClient.convertToType(data['ranges'], [PolicyV1beta1IDRange]);
            }
            if (data.hasOwnProperty('rule')) {
                obj['rule'] = ApiClient.convertToType(data['rule'], 'String');
            }
        }
        return obj;
    }

    /**
    * ranges are the allowed ranges of supplemental groups.  If you would like to force a single supplemental group then supply a single range with the same start and end. Required for MustRunAs.
    * @member {Array.<module:client/client.models/PolicyV1beta1IDRange>} ranges
    */
    ranges = undefined;
    /**
    * rule is the strategy that will dictate what supplemental groups is used in the SecurityContext.
    * @member {String} rule
    */
    rule = undefined;








}


