/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PolicyV1beta1HostPortRange model module.
* @module client/client.models/PolicyV1beta1HostPortRange
* @version 0.1
*/
export default class PolicyV1beta1HostPortRange {
    /**
    * Constructs a new <code>PolicyV1beta1HostPortRange</code>.
    * HostPortRange defines a range of host ports that will be enabled by a policy for pods to use.  It requires both the start and end to be defined.
    * @alias module:client/client.models/PolicyV1beta1HostPortRange
    * @class
    * @param max {Number} max is the end of the range, inclusive.
    * @param min {Number} min is the start of the range, inclusive.
    */

    constructor(max, min) {
        

        
        

        this['max'] = max;this['min'] = min;

        
    }

    /**
    * Constructs a <code>PolicyV1beta1HostPortRange</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/PolicyV1beta1HostPortRange} obj Optional instance to populate.
    * @return {module:client/client.models/PolicyV1beta1HostPortRange} The populated <code>PolicyV1beta1HostPortRange</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PolicyV1beta1HostPortRange();

            
            
            

            if (data.hasOwnProperty('max')) {
                obj['max'] = ApiClient.convertToType(data['max'], 'Number');
            }
            if (data.hasOwnProperty('min')) {
                obj['min'] = ApiClient.convertToType(data['min'], 'Number');
            }
        }
        return obj;
    }

    /**
    * max is the end of the range, inclusive.
    * @member {Number} max
    */
    max = undefined;
    /**
    * min is the start of the range, inclusive.
    * @member {Number} min
    */
    min = undefined;








}


