/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1APIServiceCondition from './V1APIServiceCondition';





/**
* The V1APIServiceStatus model module.
* @module client/client.models/V1APIServiceStatus
* @version 0.1
*/
export default class V1APIServiceStatus {
    /**
    * Constructs a new <code>V1APIServiceStatus</code>.
    * APIServiceStatus contains derived information about an API server
    * @alias module:client/client.models/V1APIServiceStatus
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1APIServiceStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1APIServiceStatus} obj Optional instance to populate.
    * @return {module:client/client.models/V1APIServiceStatus} The populated <code>V1APIServiceStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1APIServiceStatus();

            
            
            

            if (data.hasOwnProperty('conditions')) {
                obj['conditions'] = ApiClient.convertToType(data['conditions'], [V1APIServiceCondition]);
            }
        }
        return obj;
    }

    /**
    * Current service state of apiService.
    * @member {Array.<module:client/client.models/V1APIServiceCondition>} conditions
    */
    conditions = undefined;








}


