/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1beta1CustomResourceColumnDefinition from './V1beta1CustomResourceColumnDefinition';
import V1beta1CustomResourceConversion from './V1beta1CustomResourceConversion';
import V1beta1CustomResourceDefinitionNames from './V1beta1CustomResourceDefinitionNames';
import V1beta1CustomResourceDefinitionVersion from './V1beta1CustomResourceDefinitionVersion';
import V1beta1CustomResourceSubresources from './V1beta1CustomResourceSubresources';
import V1beta1CustomResourceValidation from './V1beta1CustomResourceValidation';





/**
* The V1beta1CustomResourceDefinitionSpec model module.
* @module client/client.models/V1beta1CustomResourceDefinitionSpec
* @version 0.1
*/
export default class V1beta1CustomResourceDefinitionSpec {
    /**
    * Constructs a new <code>V1beta1CustomResourceDefinitionSpec</code>.
    * CustomResourceDefinitionSpec describes how a user wants their resource to appear
    * @alias module:client/client.models/V1beta1CustomResourceDefinitionSpec
    * @class
    * @param group {String} Group is the group this resource belongs in
    * @param names {module:client/client.models/V1beta1CustomResourceDefinitionNames} Names are the names used to describe this custom resource
    * @param scope {String} Scope indicates whether this resource is cluster or namespace scoped.  Default is namespaced
    */

    constructor(group, names, scope) {
        

        
        

        this['group'] = group;this['names'] = names;this['scope'] = scope;

        
    }

    /**
    * Constructs a <code>V1beta1CustomResourceDefinitionSpec</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1beta1CustomResourceDefinitionSpec} obj Optional instance to populate.
    * @return {module:client/client.models/V1beta1CustomResourceDefinitionSpec} The populated <code>V1beta1CustomResourceDefinitionSpec</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1CustomResourceDefinitionSpec();

            
            
            

            if (data.hasOwnProperty('additionalPrinterColumns')) {
                obj['additionalPrinterColumns'] = ApiClient.convertToType(data['additionalPrinterColumns'], [V1beta1CustomResourceColumnDefinition]);
            }
            if (data.hasOwnProperty('conversion')) {
                obj['conversion'] = V1beta1CustomResourceConversion.constructFromObject(data['conversion']);
            }
            if (data.hasOwnProperty('group')) {
                obj['group'] = ApiClient.convertToType(data['group'], 'String');
            }
            if (data.hasOwnProperty('names')) {
                obj['names'] = V1beta1CustomResourceDefinitionNames.constructFromObject(data['names']);
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
            if (data.hasOwnProperty('subresources')) {
                obj['subresources'] = V1beta1CustomResourceSubresources.constructFromObject(data['subresources']);
            }
            if (data.hasOwnProperty('validation')) {
                obj['validation'] = V1beta1CustomResourceValidation.constructFromObject(data['validation']);
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('versions')) {
                obj['versions'] = ApiClient.convertToType(data['versions'], [V1beta1CustomResourceDefinitionVersion]);
            }
        }
        return obj;
    }

    /**
    * AdditionalPrinterColumns are additional columns shown e.g. in kubectl next to the name. Defaults to a created-at column. Optional, the global columns for all versions. Top-level and per-version columns are mutually exclusive.
    * @member {Array.<module:client/client.models/V1beta1CustomResourceColumnDefinition>} additionalPrinterColumns
    */
    additionalPrinterColumns = undefined;
    /**
    * `conversion` defines conversion settings for the CRD.
    * @member {module:client/client.models/V1beta1CustomResourceConversion} conversion
    */
    conversion = undefined;
    /**
    * Group is the group this resource belongs in
    * @member {String} group
    */
    group = undefined;
    /**
    * Names are the names used to describe this custom resource
    * @member {module:client/client.models/V1beta1CustomResourceDefinitionNames} names
    */
    names = undefined;
    /**
    * Scope indicates whether this resource is cluster or namespace scoped.  Default is namespaced
    * @member {String} scope
    */
    scope = undefined;
    /**
    * Subresources describes the subresources for CustomResource Optional, the global subresources for all versions. Top-level and per-version subresources are mutually exclusive.
    * @member {module:client/client.models/V1beta1CustomResourceSubresources} subresources
    */
    subresources = undefined;
    /**
    * Validation describes the validation methods for CustomResources Optional, the global validation schema for all versions. Top-level and per-version schemas are mutually exclusive.
    * @member {module:client/client.models/V1beta1CustomResourceValidation} validation
    */
    validation = undefined;
    /**
    * Version is the version this resource belongs in Should be always first item in Versions field if provided. Optional, but at least one of Version or Versions must be set. Deprecated: Please use `Versions`.
    * @member {String} version
    */
    version = undefined;
    /**
    * Versions is the list of all supported versions for this resource. If Version field is provided, this field is optional. Validation: All versions must use the same validation schema for now. i.e., top level Validation field is applied to all of these versions. Order: The version name will be used to compute the order. If the version string is \"kube-like\", it will sort above non \"kube-like\" version strings, which are ordered lexicographically. \"Kube-like\" versions start with a \"v\", then are followed by a number (the major version), then optionally the string \"alpha\" or \"beta\" and another number (the minor version). These are sorted first by GA > beta > alpha (where GA is a version with no suffix such as beta or alpha), and then by comparing major version, then minor version. An example sorted list of versions: v10, v2, v1, v11beta2, v10beta3, v3beta1, v12alpha1, v11alpha2, foo1, foo10.
    * @member {Array.<module:client/client.models/V1beta1CustomResourceDefinitionVersion>} versions
    */
    versions = undefined;








}


