/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1beta1RuleWithOperations model module.
* @module client/client.models/V1beta1RuleWithOperations
* @version 0.1
*/
export default class V1beta1RuleWithOperations {
    /**
    * Constructs a new <code>V1beta1RuleWithOperations</code>.
    * RuleWithOperations is a tuple of Operations and Resources. It is recommended to make sure that all the tuple expansions are valid.
    * @alias module:client/client.models/V1beta1RuleWithOperations
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1RuleWithOperations</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1beta1RuleWithOperations} obj Optional instance to populate.
    * @return {module:client/client.models/V1beta1RuleWithOperations} The populated <code>V1beta1RuleWithOperations</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1RuleWithOperations();

            
            
            

            if (data.hasOwnProperty('apiGroups')) {
                obj['apiGroups'] = ApiClient.convertToType(data['apiGroups'], ['String']);
            }
            if (data.hasOwnProperty('apiVersions')) {
                obj['apiVersions'] = ApiClient.convertToType(data['apiVersions'], ['String']);
            }
            if (data.hasOwnProperty('operations')) {
                obj['operations'] = ApiClient.convertToType(data['operations'], ['String']);
            }
            if (data.hasOwnProperty('resources')) {
                obj['resources'] = ApiClient.convertToType(data['resources'], ['String']);
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
        }
        return obj;
    }

    /**
    * APIGroups is the API groups the resources belong to. '*' is all groups. If '*' is present, the length of the slice must be one. Required.
    * @member {Array.<String>} apiGroups
    */
    apiGroups = undefined;
    /**
    * APIVersions is the API versions the resources belong to. '*' is all versions. If '*' is present, the length of the slice must be one. Required.
    * @member {Array.<String>} apiVersions
    */
    apiVersions = undefined;
    /**
    * Operations is the operations the admission hook cares about - CREATE, UPDATE, or * for all operations. If '*' is present, the length of the slice must be one. Required.
    * @member {Array.<String>} operations
    */
    operations = undefined;
    /**
    * Resources is a list of resources this rule applies to.  For example: 'pods' means pods. 'pods/log' means the log subresource of pods. '*' means all resources, but not subresources. 'pods/_*' means all subresources of pods. '*_/scale' means all scale subresources. '*_/_*' means all resources and their subresources.  If wildcard is present, the validation rule will ensure resources do not overlap with each other.  Depending on the enclosing object, subresources might not be allowed. Required.
    * @member {Array.<String>} resources
    */
    resources = undefined;
    /**
    * scope specifies the scope of this rule. Valid values are \"Cluster\", \"Namespaced\", and \"*\" \"Cluster\" means that only cluster-scoped resources will match this rule. Namespace API objects are cluster-scoped. \"Namespaced\" means that only namespaced resources will match this rule. \"*\" means that there are no scope restrictions. Subresources match the scope of their parent resource. Default is \"*\".
    * @member {String} scope
    */
    scope = undefined;








}


