/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1beta1VolumeError model module.
* @module client/client.models/V1beta1VolumeError
* @version 0.1
*/
export default class V1beta1VolumeError {
    /**
    * Constructs a new <code>V1beta1VolumeError</code>.
    * VolumeError captures an error encountered during a volume operation.
    * @alias module:client/client.models/V1beta1VolumeError
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1VolumeError</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1beta1VolumeError} obj Optional instance to populate.
    * @return {module:client/client.models/V1beta1VolumeError} The populated <code>V1beta1VolumeError</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1VolumeError();

            
            
            

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
        }
        return obj;
    }

    /**
    * String detailing the error encountered during Attach or Detach operation. This string may be logged, so it should not contain sensitive information.
    * @member {String} message
    */
    message = undefined;
    /**
    * Time the error was encountered.
    * @member {Date} time
    */
    time = undefined;








}


