/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ApiextensionsV1beta1WebhookClientConfig from './ApiextensionsV1beta1WebhookClientConfig';





/**
* The V1beta1CustomResourceConversion model module.
* @module client/client.models/V1beta1CustomResourceConversion
* @version 0.1
*/
export default class V1beta1CustomResourceConversion {
    /**
    * Constructs a new <code>V1beta1CustomResourceConversion</code>.
    * CustomResourceConversion describes how to convert different versions of a CR.
    * @alias module:client/client.models/V1beta1CustomResourceConversion
    * @class
    * @param strategy {String} `strategy` specifies the conversion strategy. Allowed values are: - `None`: The converter only change the apiVersion and would not touch any other field in the CR. - `Webhook`: API Server will call to an external webhook to do the conversion. Additional information is needed for this option.
    */

    constructor(strategy) {
        

        
        

        this['strategy'] = strategy;

        
    }

    /**
    * Constructs a <code>V1beta1CustomResourceConversion</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1beta1CustomResourceConversion} obj Optional instance to populate.
    * @return {module:client/client.models/V1beta1CustomResourceConversion} The populated <code>V1beta1CustomResourceConversion</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1CustomResourceConversion();

            
            
            

            if (data.hasOwnProperty('conversionReviewVersions')) {
                obj['conversionReviewVersions'] = ApiClient.convertToType(data['conversionReviewVersions'], ['String']);
            }
            if (data.hasOwnProperty('strategy')) {
                obj['strategy'] = ApiClient.convertToType(data['strategy'], 'String');
            }
            if (data.hasOwnProperty('webhookClientConfig')) {
                obj['webhookClientConfig'] = ApiextensionsV1beta1WebhookClientConfig.constructFromObject(data['webhookClientConfig']);
            }
        }
        return obj;
    }

    /**
    * ConversionReviewVersions is an ordered list of preferred `ConversionReview` versions the Webhook expects. API server will try to use first version in the list which it supports. If none of the versions specified in this list supported by API server, conversion will fail for this object. If a persisted Webhook configuration specifies allowed versions and does not include any versions known to the API Server, calls to the webhook will fail. Default to `['v1beta1']`.
    * @member {Array.<String>} conversionReviewVersions
    */
    conversionReviewVersions = undefined;
    /**
    * `strategy` specifies the conversion strategy. Allowed values are: - `None`: The converter only change the apiVersion and would not touch any other field in the CR. - `Webhook`: API Server will call to an external webhook to do the conversion. Additional information is needed for this option.
    * @member {String} strategy
    */
    strategy = undefined;
    /**
    * `webhookClientConfig` is the instructions for how to call the webhook if strategy is `Webhook`. This field is alpha-level and is only honored by servers that enable the CustomResourceWebhookConversion feature.
    * @member {module:client/client.models/ApiextensionsV1beta1WebhookClientConfig} webhookClientConfig
    */
    webhookClientConfig = undefined;








}


