/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1beta1UserInfo from './V1beta1UserInfo';





/**
* The V1beta1TokenReviewStatus model module.
* @module client/client.models/V1beta1TokenReviewStatus
* @version 0.1
*/
export default class V1beta1TokenReviewStatus {
    /**
    * Constructs a new <code>V1beta1TokenReviewStatus</code>.
    * TokenReviewStatus is the result of the token authentication request.
    * @alias module:client/client.models/V1beta1TokenReviewStatus
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1beta1TokenReviewStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1beta1TokenReviewStatus} obj Optional instance to populate.
    * @return {module:client/client.models/V1beta1TokenReviewStatus} The populated <code>V1beta1TokenReviewStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1beta1TokenReviewStatus();

            
            
            

            if (data.hasOwnProperty('audiences')) {
                obj['audiences'] = ApiClient.convertToType(data['audiences'], ['String']);
            }
            if (data.hasOwnProperty('authenticated')) {
                obj['authenticated'] = ApiClient.convertToType(data['authenticated'], 'Boolean');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = V1beta1UserInfo.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
    * Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token's audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is \"true\", the token is valid against the audience of the Kubernetes API server.
    * @member {Array.<String>} audiences
    */
    audiences = undefined;
    /**
    * Authenticated indicates that the token was associated with a known user.
    * @member {Boolean} authenticated
    */
    authenticated = undefined;
    /**
    * Error indicates that the token couldn't be checked
    * @member {String} error
    */
    error = undefined;
    /**
    * User is the UserInfo associated with the provided token.
    * @member {module:client/client.models/V1beta1UserInfo} user
    */
    user = undefined;








}


