/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1SecretReference from './V1SecretReference';





/**
* The V1CinderPersistentVolumeSource model module.
* @module client/client.models/V1CinderPersistentVolumeSource
* @version 0.1
*/
export default class V1CinderPersistentVolumeSource {
    /**
    * Constructs a new <code>V1CinderPersistentVolumeSource</code>.
    * Represents a cinder volume resource in Openstack. A Cinder volume must exist before mounting to a container. The volume must also be in the same region as the kubelet. Cinder volumes support ownership management and SELinux relabeling.
    * @alias module:client/client.models/V1CinderPersistentVolumeSource
    * @class
    * @param volumeID {String} volume id used to identify the volume in cinder More info: https://releases.k8s.io/HEAD/examples/mysql-cinder-pd/README.md
    */

    constructor(volumeID) {
        

        
        

        this['volumeID'] = volumeID;

        
    }

    /**
    * Constructs a <code>V1CinderPersistentVolumeSource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1CinderPersistentVolumeSource} obj Optional instance to populate.
    * @return {module:client/client.models/V1CinderPersistentVolumeSource} The populated <code>V1CinderPersistentVolumeSource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1CinderPersistentVolumeSource();

            
            
            

            if (data.hasOwnProperty('fsType')) {
                obj['fsType'] = ApiClient.convertToType(data['fsType'], 'String');
            }
            if (data.hasOwnProperty('readOnly')) {
                obj['readOnly'] = ApiClient.convertToType(data['readOnly'], 'Boolean');
            }
            if (data.hasOwnProperty('secretRef')) {
                obj['secretRef'] = V1SecretReference.constructFromObject(data['secretRef']);
            }
            if (data.hasOwnProperty('volumeID')) {
                obj['volumeID'] = ApiClient.convertToType(data['volumeID'], 'String');
            }
        }
        return obj;
    }

    /**
    * Filesystem type to mount. Must be a filesystem type supported by the host operating system. Examples: \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. More info: https://releases.k8s.io/HEAD/examples/mysql-cinder-pd/README.md
    * @member {String} fsType
    */
    fsType = undefined;
    /**
    * Optional: Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. More info: https://releases.k8s.io/HEAD/examples/mysql-cinder-pd/README.md
    * @member {Boolean} readOnly
    */
    readOnly = undefined;
    /**
    * Optional: points to a secret object containing parameters used to connect to OpenStack.
    * @member {module:client/client.models/V1SecretReference} secretRef
    */
    secretRef = undefined;
    /**
    * volume id used to identify the volume in cinder More info: https://releases.k8s.io/HEAD/examples/mysql-cinder-pd/README.md
    * @member {String} volumeID
    */
    volumeID = undefined;








}


