/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1LoadBalancerIngress from './V1LoadBalancerIngress';





/**
* The V1LoadBalancerStatus model module.
* @module client/client.models/V1LoadBalancerStatus
* @version 0.1
*/
export default class V1LoadBalancerStatus {
    /**
    * Constructs a new <code>V1LoadBalancerStatus</code>.
    * LoadBalancerStatus represents the status of a load-balancer.
    * @alias module:client/client.models/V1LoadBalancerStatus
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1LoadBalancerStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1LoadBalancerStatus} obj Optional instance to populate.
    * @return {module:client/client.models/V1LoadBalancerStatus} The populated <code>V1LoadBalancerStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1LoadBalancerStatus();

            
            
            

            if (data.hasOwnProperty('ingress')) {
                obj['ingress'] = ApiClient.convertToType(data['ingress'], [V1LoadBalancerIngress]);
            }
        }
        return obj;
    }

    /**
    * Ingress is a list containing ingress points for the load-balancer. Traffic intended for the service should be sent to these ingress points.
    * @member {Array.<module:client/client.models/V1LoadBalancerIngress>} ingress
    */
    ingress = undefined;








}


