/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1LocalVolumeSource model module.
* @module client/client.models/V1LocalVolumeSource
* @version 0.1
*/
export default class V1LocalVolumeSource {
    /**
    * Constructs a new <code>V1LocalVolumeSource</code>.
    * Local represents directly-attached storage with node affinity (Beta feature)
    * @alias module:client/client.models/V1LocalVolumeSource
    * @class
    * @param path {String} The full path to the volume on the node. It can be either a directory or block device (disk, partition, ...).
    */

    constructor(path) {
        

        
        

        this['path'] = path;

        
    }

    /**
    * Constructs a <code>V1LocalVolumeSource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1LocalVolumeSource} obj Optional instance to populate.
    * @return {module:client/client.models/V1LocalVolumeSource} The populated <code>V1LocalVolumeSource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1LocalVolumeSource();

            
            
            

            if (data.hasOwnProperty('fsType')) {
                obj['fsType'] = ApiClient.convertToType(data['fsType'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }

    /**
    * Filesystem type to mount. It applies only when the Path is a block device. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". The default value is to auto-select a fileystem if unspecified.
    * @member {String} fsType
    */
    fsType = undefined;
    /**
    * The full path to the volume on the node. It can be either a directory or block device (disk, partition, ...).
    * @member {String} path
    */
    path = undefined;








}


