/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1ManagedFieldsEntry model module.
* @module client/client.models/V1ManagedFieldsEntry
* @version 0.1
*/
export default class V1ManagedFieldsEntry {
    /**
    * Constructs a new <code>V1ManagedFieldsEntry</code>.
    * ManagedFieldsEntry is a workflow-id, a FieldSet and the group version of the resource that the fieldset applies to.
    * @alias module:client/client.models/V1ManagedFieldsEntry
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1ManagedFieldsEntry</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1ManagedFieldsEntry} obj Optional instance to populate.
    * @return {module:client/client.models/V1ManagedFieldsEntry} The populated <code>V1ManagedFieldsEntry</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ManagedFieldsEntry();

            
            
            

            if (data.hasOwnProperty('apiVersion')) {
                obj['apiVersion'] = ApiClient.convertToType(data['apiVersion'], 'String');
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], Object);
            }
            if (data.hasOwnProperty('manager')) {
                obj['manager'] = ApiClient.convertToType(data['manager'], 'String');
            }
            if (data.hasOwnProperty('operation')) {
                obj['operation'] = ApiClient.convertToType(data['operation'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
        }
        return obj;
    }

    /**
    * APIVersion defines the version of this resource that this field set applies to. The format is \"group/version\" just like the top-level APIVersion field. It is necessary to track the version of a field set because it cannot be automatically converted.
    * @member {String} apiVersion
    */
    apiVersion = undefined;
    /**
    * Fields identifies a set of fields.
    * @member {Object} fields
    */
    fields = undefined;
    /**
    * Manager is an identifier of the workflow managing these fields.
    * @member {String} manager
    */
    manager = undefined;
    /**
    * Operation is the type of operation which lead to this ManagedFieldsEntry being created. The only valid values for this field are 'Apply' and 'Update'.
    * @member {String} operation
    */
    operation = undefined;
    /**
    * Time is timestamp of when these fields were set. It should always be empty if Operation is 'Apply'
    * @member {Date} time
    */
    time = undefined;








}


