/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1NodeAddress model module.
* @module client/client.models/V1NodeAddress
* @version 0.1
*/
export default class V1NodeAddress {
    /**
    * Constructs a new <code>V1NodeAddress</code>.
    * NodeAddress contains information for the node&#39;s address.
    * @alias module:client/client.models/V1NodeAddress
    * @class
    * @param address {String} The node address.
    * @param type {String} Node address type, one of Hostname, ExternalIP or InternalIP.
    */

    constructor(address, type) {
        

        
        

        this['address'] = address;this['type'] = type;

        
    }

    /**
    * Constructs a <code>V1NodeAddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1NodeAddress} obj Optional instance to populate.
    * @return {module:client/client.models/V1NodeAddress} The populated <code>V1NodeAddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1NodeAddress();

            
            
            

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * The node address.
    * @member {String} address
    */
    address = undefined;
    /**
    * Node address type, one of Hostname, ExternalIP or InternalIP.
    * @member {String} type
    */
    type = undefined;








}


