/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1PodReadinessGate model module.
* @module client/client.models/V1PodReadinessGate
* @version 0.1
*/
export default class V1PodReadinessGate {
    /**
    * Constructs a new <code>V1PodReadinessGate</code>.
    * PodReadinessGate contains the reference to a pod condition
    * @alias module:client/client.models/V1PodReadinessGate
    * @class
    * @param conditionType {String} ConditionType refers to a condition in the pod's condition list with matching type.
    */

    constructor(conditionType) {
        

        
        

        this['conditionType'] = conditionType;

        
    }

    /**
    * Constructs a <code>V1PodReadinessGate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1PodReadinessGate} obj Optional instance to populate.
    * @return {module:client/client.models/V1PodReadinessGate} The populated <code>V1PodReadinessGate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1PodReadinessGate();

            
            
            

            if (data.hasOwnProperty('conditionType')) {
                obj['conditionType'] = ApiClient.convertToType(data['conditionType'], 'String');
            }
        }
        return obj;
    }

    /**
    * ConditionType refers to a condition in the pod's condition list with matching type.
    * @member {String} conditionType
    */
    conditionType = undefined;








}


