/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1ScopeSelector from './V1ScopeSelector';





/**
* The V1ResourceQuotaSpec model module.
* @module client/client.models/V1ResourceQuotaSpec
* @version 0.1
*/
export default class V1ResourceQuotaSpec {
    /**
    * Constructs a new <code>V1ResourceQuotaSpec</code>.
    * ResourceQuotaSpec defines the desired hard limits to enforce for Quota.
    * @alias module:client/client.models/V1ResourceQuotaSpec
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1ResourceQuotaSpec</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1ResourceQuotaSpec} obj Optional instance to populate.
    * @return {module:client/client.models/V1ResourceQuotaSpec} The populated <code>V1ResourceQuotaSpec</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ResourceQuotaSpec();

            
            
            

            if (data.hasOwnProperty('hard')) {
                obj['hard'] = ApiClient.convertToType(data['hard'], {'String': 'String'});
            }
            if (data.hasOwnProperty('scopeSelector')) {
                obj['scopeSelector'] = V1ScopeSelector.constructFromObject(data['scopeSelector']);
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], ['String']);
            }
        }
        return obj;
    }

    /**
    * hard is the set of desired hard limits for each named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/
    * @member {Object.<String, String>} hard
    */
    hard = undefined;
    /**
    * scopeSelector is also a collection of filters like scopes that must match each object tracked by a quota but expressed using ScopeSelectorOperator in combination with possible values. For a resource to match, both scopes AND scopeSelector (if specified in spec), must be matched.
    * @member {module:client/client.models/V1ScopeSelector} scopeSelector
    */
    scopeSelector = undefined;
    /**
    * A collection of filters that must match each object tracked by a quota. If not specified, the quota matches all objects.
    * @member {Array.<String>} scopes
    */
    scopes = undefined;








}


