/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1ServiceAccountTokenProjection model module.
* @module client/client.models/V1ServiceAccountTokenProjection
* @version 0.1
*/
export default class V1ServiceAccountTokenProjection {
    /**
    * Constructs a new <code>V1ServiceAccountTokenProjection</code>.
    * ServiceAccountTokenProjection represents a projected service account token volume. This projection can be used to insert a service account token into the pods runtime filesystem for use against APIs (Kubernetes API Server or otherwise).
    * @alias module:client/client.models/V1ServiceAccountTokenProjection
    * @class
    * @param path {String} Path is the path relative to the mount point of the file to project the token into.
    */

    constructor(path) {
        

        
        

        this['path'] = path;

        
    }

    /**
    * Constructs a <code>V1ServiceAccountTokenProjection</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1ServiceAccountTokenProjection} obj Optional instance to populate.
    * @return {module:client/client.models/V1ServiceAccountTokenProjection} The populated <code>V1ServiceAccountTokenProjection</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ServiceAccountTokenProjection();

            
            
            

            if (data.hasOwnProperty('audience')) {
                obj['audience'] = ApiClient.convertToType(data['audience'], 'String');
            }
            if (data.hasOwnProperty('expirationSeconds')) {
                obj['expirationSeconds'] = ApiClient.convertToType(data['expirationSeconds'], 'Number');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }

    /**
    * Audience is the intended audience of the token. A recipient of a token must identify itself with an identifier specified in the audience of the token, and otherwise should reject the token. The audience defaults to the identifier of the apiserver.
    * @member {String} audience
    */
    audience = undefined;
    /**
    * ExpirationSeconds is the requested duration of validity of the service account token. As the token approaches expiration, the kubelet volume plugin will proactively rotate the service account token. The kubelet will start trying to rotate the token if the token is older than 80 percent of its time to live or if the token is older than 24 hours.Defaults to 1 hour and must be at least 10 minutes.
    * @member {Number} expirationSeconds
    */
    expirationSeconds = undefined;
    /**
    * Path is the path relative to the mount point of the file to project the token into.
    * @member {String} path
    */
    path = undefined;








}


