/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1Sysctl model module.
* @module client/client.models/V1Sysctl
* @version 0.1
*/
export default class V1Sysctl {
    /**
    * Constructs a new <code>V1Sysctl</code>.
    * Sysctl defines a kernel parameter to be set
    * @alias module:client/client.models/V1Sysctl
    * @class
    * @param name {String} Name of a property to set
    * @param value {String} Value of a property to set
    */

    constructor(name, value) {
        

        
        

        this['name'] = name;this['value'] = value;

        
    }

    /**
    * Constructs a <code>V1Sysctl</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1Sysctl} obj Optional instance to populate.
    * @return {module:client/client.models/V1Sysctl} The populated <code>V1Sysctl</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1Sysctl();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * Name of a property to set
    * @member {String} name
    */
    name = undefined;
    /**
    * Value of a property to set
    * @member {String} value
    */
    value = undefined;








}


