/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The V1VolumeAttachmentSource model module.
* @module client/client.models/V1VolumeAttachmentSource
* @version 0.1
*/
export default class V1VolumeAttachmentSource {
    /**
    * Constructs a new <code>V1VolumeAttachmentSource</code>.
    * VolumeAttachmentSource represents a volume that should be attached. Right now only PersistenVolumes can be attached via external attacher, in future we may allow also inline volumes in pods. Exactly one member can be set.
    * @alias module:client/client.models/V1VolumeAttachmentSource
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>V1VolumeAttachmentSource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V1VolumeAttachmentSource} obj Optional instance to populate.
    * @return {module:client/client.models/V1VolumeAttachmentSource} The populated <code>V1VolumeAttachmentSource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1VolumeAttachmentSource();

            
            
            

            if (data.hasOwnProperty('persistentVolumeName')) {
                obj['persistentVolumeName'] = ApiClient.convertToType(data['persistentVolumeName'], 'String');
            }
        }
        return obj;
    }

    /**
    * Name of the persistent volume to attach.
    * @member {String} persistentVolumeName
    */
    persistentVolumeName = undefined;








}


