/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V2beta2MetricIdentifier from './V2beta2MetricIdentifier';
import V2beta2MetricValueStatus from './V2beta2MetricValueStatus';





/**
* The V2beta2PodsMetricStatus model module.
* @module client/client.models/V2beta2PodsMetricStatus
* @version 0.1
*/
export default class V2beta2PodsMetricStatus {
    /**
    * Constructs a new <code>V2beta2PodsMetricStatus</code>.
    * PodsMetricStatus indicates the current value of a metric describing each pod in the current scale target (for example, transactions-processed-per-second).
    * @alias module:client/client.models/V2beta2PodsMetricStatus
    * @class
    * @param current {module:client/client.models/V2beta2MetricValueStatus} current contains the current value for the given metric
    * @param metric {module:client/client.models/V2beta2MetricIdentifier} metric identifies the target metric by name and selector
    */

    constructor(current, metric) {
        

        
        

        this['current'] = current;this['metric'] = metric;

        
    }

    /**
    * Constructs a <code>V2beta2PodsMetricStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V2beta2PodsMetricStatus} obj Optional instance to populate.
    * @return {module:client/client.models/V2beta2PodsMetricStatus} The populated <code>V2beta2PodsMetricStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V2beta2PodsMetricStatus();

            
            
            

            if (data.hasOwnProperty('current')) {
                obj['current'] = V2beta2MetricValueStatus.constructFromObject(data['current']);
            }
            if (data.hasOwnProperty('metric')) {
                obj['metric'] = V2beta2MetricIdentifier.constructFromObject(data['metric']);
            }
        }
        return obj;
    }

    /**
    * current contains the current value for the given metric
    * @member {module:client/client.models/V2beta2MetricValueStatus} current
    */
    current = undefined;
    /**
    * metric identifies the target metric by name and selector
    * @member {module:client/client.models/V2beta2MetricIdentifier} metric
    */
    metric = undefined;








}


