/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import V1LabelSelector from './V1LabelSelector';





/**
* The V2beta1PodsMetricStatus model module.
* @module client/client.models/V2beta1PodsMetricStatus
* @version 0.1
*/
export default class V2beta1PodsMetricStatus {
    /**
    * Constructs a new <code>V2beta1PodsMetricStatus</code>.
    * PodsMetricStatus indicates the current value of a metric describing each pod in the current scale target (for example, transactions-processed-per-second).
    * @alias module:client/client.models/V2beta1PodsMetricStatus
    * @class
    * @param currentAverageValue {String} currentAverageValue is the current value of the average of the metric across all relevant pods (as a quantity)
    * @param metricName {String} metricName is the name of the metric in question
    */

    constructor(currentAverageValue, metricName) {
        

        
        

        this['currentAverageValue'] = currentAverageValue;this['metricName'] = metricName;

        
    }

    /**
    * Constructs a <code>V2beta1PodsMetricStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:client/client.models/V2beta1PodsMetricStatus} obj Optional instance to populate.
    * @return {module:client/client.models/V2beta1PodsMetricStatus} The populated <code>V2beta1PodsMetricStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V2beta1PodsMetricStatus();

            
            
            

            if (data.hasOwnProperty('currentAverageValue')) {
                obj['currentAverageValue'] = ApiClient.convertToType(data['currentAverageValue'], 'String');
            }
            if (data.hasOwnProperty('metricName')) {
                obj['metricName'] = ApiClient.convertToType(data['metricName'], 'String');
            }
            if (data.hasOwnProperty('selector')) {
                obj['selector'] = V1LabelSelector.constructFromObject(data['selector']);
            }
        }
        return obj;
    }

    /**
    * currentAverageValue is the current value of the average of the metric across all relevant pods (as a quantity)
    * @member {String} currentAverageValue
    */
    currentAverageValue = undefined;
    /**
    * metricName is the name of the metric in question
    * @member {String} metricName
    */
    metricName = undefined;
    /**
    * selector is the string-encoded form of a standard kubernetes label selector for the given metric When set in the PodsMetricSource, it is passed as an additional parameter to the metrics server for more specific metrics scoping. When unset, just the metricName will be used to gather metrics.
    * @member {module:client/client.models/V1LabelSelector} selector
    */
    selector = undefined;








}


