/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.15.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KubernetesJsClient);
  }
}(this, function(expect, KubernetesJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KubernetesJsClient.Node_v1beta1Api();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Node_v1beta1Api', function() {
    describe('createRuntimeClass', function() {
      it('should call createRuntimeClass successfully', function(done) {
        //uncomment below and update the code to test createRuntimeClass
        //instance.createRuntimeClass(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCollectionRuntimeClass', function() {
      it('should call deleteCollectionRuntimeClass successfully', function(done) {
        //uncomment below and update the code to test deleteCollectionRuntimeClass
        //instance.deleteCollectionRuntimeClass(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRuntimeClass', function() {
      it('should call deleteRuntimeClass successfully', function(done) {
        //uncomment below and update the code to test deleteRuntimeClass
        //instance.deleteRuntimeClass(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAPIResources', function() {
      it('should call getAPIResources successfully', function(done) {
        //uncomment below and update the code to test getAPIResources
        //instance.getAPIResources(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listRuntimeClass', function() {
      it('should call listRuntimeClass successfully', function(done) {
        //uncomment below and update the code to test listRuntimeClass
        //instance.listRuntimeClass(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchRuntimeClass', function() {
      it('should call patchRuntimeClass successfully', function(done) {
        //uncomment below and update the code to test patchRuntimeClass
        //instance.patchRuntimeClass(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readRuntimeClass', function() {
      it('should call readRuntimeClass successfully', function(done) {
        //uncomment below and update the code to test readRuntimeClass
        //instance.readRuntimeClass(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceRuntimeClass', function() {
      it('should call replaceRuntimeClass successfully', function(done) {
        //uncomment below and update the code to test replaceRuntimeClass
        //instance.replaceRuntimeClass(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
